### ISSUE TITLE
Scraping Answers Returning Errors

### ISSUE THREAD

**Issue by dneanover** [nathanbraun/ltcwff-files#2]
#5.1.3 `ffc_player_info()

Found two issues:
1. Table structure and headers have changed.  New Headers: Age, Birthdate, Height, Weight, College, Year, Pick, Team
2. `dict_of_parsed_rows` fails with this error. **ValueError: not enough values to unpack (expected 2, got 1)**

**Comment by nathanbraun** [comment]
Fixed this, thanks for the heads up!
